# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install sharpie
      run: brew cask install objectivesharpie

    - name: Run make
      run: make
    
    - name: setup-xamarin
      uses: maxim-lobanov/setup-xamarin@v1.1
      with:
        xamarin-ios-version: latest
        mono-version: latest
        xcode-version: latest
        
    - name: Run 'MSBuild'
      run: MSBuild -p:Configuration=Release -restore:True
    
    - name: Run 'nuget pack'
      run: nuget pack -Symbols -Verbosity Detailed -OutputDirectory "Output"
    
    - name: Push on Github
      run: dotnet nuget push "Output" --source "github"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Xamarin.Nordic.DFU.iOS
        # Directory containing files to upload
        path: Output
